## CELL 1 - Cek Environment

In [20]:
import sys
from pathlib import Path

print("Python executable:")
print(sys.executable)

print("\nCurrent working directory:")
print(Path.cwd())

Python executable:
e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\.venv\Scripts\python.exe

Current working directory:
e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\notebooks

## Cell 2 — Cek library dasar

In [21]:
import pandas as pd
import openpyxl
import matplotlib

print("pandas version:", pd.__version__)
print("openpyxl version:", openpyxl.__version__)
print("matplotlib version:", matplotlib.__version__)

pandas version: 3.0.3
openpyxl version: 3.1.5
matplotlib version: 3.11.0

## Cell 3 — Tentukan folder utama project

In [22]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

print("Project root:")
print(PROJECT_ROOT)

print("\nIsi folder project:")
for item in PROJECT_ROOT.iterdir():
    print("-", item.name)

Project root:
e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL

Isi folder project:
- .venv
- data
- docs
- notebooks
- outputs
- requirements.txt
- src

## Cell 4 — Cek folder data

In [23]:
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
LABEL_DIR = DATA_DIR / "label"

print("Data folder ditemukan:", DATA_DIR.exists())
print("Raw folder ditemukan:", RAW_DIR.exists())
print("Label folder ditemukan:", LABEL_DIR.exists())

print("\nFile di data/raw:")
for file in RAW_DIR.iterdir():
    print("-", file.name)

print("\nFile di data/label:")
for file in LABEL_DIR.iterdir():
    print("-", file.name)

Data folder ditemukan: True
Raw folder ditemukan: True
Label folder ditemukan: True

File di data/raw:
- logs_CAK1CAB3-IF-49-02_20260122-1521.xlsx
- logs_CAK1CAB3-IF-49-03_20260122-1521.xlsx

File di data/label:
- IF-49-02_Kalkulus.pdf
- IF-49-03_Kalkulus.pdf

## Cell 5 — Ambil daftar file Excel otomatis

In [24]:
excel_files = sorted(RAW_DIR.glob("*.xlsx"))

print("Jumlah file Excel ditemukan:", len(excel_files))

for file in excel_files:
    print("-", file.name)

Jumlah file Excel ditemukan: 2
- logs_CAK1CAB3-IF-49-02_20260122-1521.xlsx
- logs_CAK1CAB3-IF-49-03_20260122-1521.xlsx

## Cell 6 — Cek sheet Excel dulu

In [25]:
for file in excel_files:
    xls = pd.ExcelFile(file)
    print("File:", file.name)
    print("Sheet:", xls.sheet_names)
    print()

File: logs_CAK1CAB3-IF-49-02_20260122-1521.xlsx
Sheet: ['Sheet1']

File: logs_CAK1CAB3-IF-49-03_20260122-1521.xlsx
Sheet: ['Sheet1']

## Cell 7 — Baca dua file Excel

In [26]:
log_02 = pd.read_excel(excel_files[0])
log_03 = pd.read_excel(excel_files[1])

print("File pertama dibaca sebagai log_02:", excel_files[0].name)
print("File kedua dibaca sebagai log_03:", excel_files[1].name)

File pertama dibaca sebagai log_02: logs_CAK1CAB3-IF-49-02_20260122-1521.xlsx
File kedua dibaca sebagai log_03: logs_CAK1CAB3-IF-49-03_20260122-1521.xlsx

## Cell 8 — Cek ukuran data

In [27]:
print("Ukuran log_02:", log_02.shape)
print("Ukuran log_03:", log_03.shape)

Ukuran log_02: (89454, 9)
Ukuran log_03: (76192, 9)

## Cell 9 — Cek nama kolom

In [28]:
print("Kolom log_02:")
print(log_02.columns.tolist())

print("\nKolom log_03:")
print(log_03.columns.tolist())

Kolom log_02:
['Time', 'User full name', 'Affected user', 'Event context', 'Component', 'Event name', 'Description', 'Origin', 'IP address']

Kolom log_03:
['Time', 'User full name', 'Affected user', 'Event context', 'Component', 'Event name', 'Description', 'Origin', 'IP address']

## Cell 10 — Lihat 5 baris pertama

In [29]:
display(log_02.head())
display(log_03.head())

,Time,User full name,Affected user,Event context,Component,Event name,Description,Origin,IP address
0,"22/01/26, 15:21:30",ADE KURNIAWAN,-,Course: KALKULUS IF-49-02 [DLW],Logs,Log report viewed,The user with id &#039;54114&#039; viewed the ...,web,103.233.100.203
1,"22/01/26, 15:20:55",ADE KURNIAWAN,-,Course: KALKULUS IF-49-02 [DLW],System,Course viewed,The user with id &#039;54114&#039; viewed the ...,web,103.233.100.203
2,"20/01/26, 15:53:58",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-02 [DLW],System,Course viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204
3,"20/01/26, 15:14:42",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-02 [DLW],Logs,Log report viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204
4,"20/01/26, 15:09:21",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-02 [DLW],Logs,Log report viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204

,Time,User full name,Affected user,Event context,Component,Event name,Description,Origin,IP address
0,"22/01/26, 15:21:32",ADE KURNIAWAN,-,Course: KALKULUS IF-49-03 [DLW],Logs,Log report viewed,The user with id &#039;54114&#039; viewed the ...,web,103.233.100.203
1,"22/01/26, 15:20:58",ADE KURNIAWAN,-,Course: KALKULUS IF-49-03 [DLW],System,Course viewed,The user with id &#039;54114&#039; viewed the ...,web,103.233.100.203
2,"20/01/26, 15:53:51",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-03 [DLW],System,Course viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204
3,"20/01/26, 15:14:23",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-03 [DLW],Logs,Log report viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204
4,"20/01/26, 15:09:17",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-03 [DLW],Logs,Log report viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204

## Cell 11 — Gabungkan dua log mentah dengan penanda kelas

In [30]:
log_02_raw = log_02.copy()
log_03_raw = log_03.copy()

log_02_raw["kelas"] = "IF-49-02"
log_03_raw["kelas"] = "IF-49-03"

log_raw = pd.concat([log_02_raw, log_03_raw], ignore_index=True)

print("Ukuran log gabungan:", log_raw.shape)
display(log_raw.head())

Ukuran log gabungan: (165646, 10)

,Time,User full name,Affected user,Event context,Component,Event name,Description,Origin,IP address,kelas
0,"22/01/26, 15:21:30",ADE KURNIAWAN,-,Course: KALKULUS IF-49-02 [DLW],Logs,Log report viewed,The user with id &#039;54114&#039; viewed the ...,web,103.233.100.203,IF-49-02
1,"22/01/26, 15:20:55",ADE KURNIAWAN,-,Course: KALKULUS IF-49-02 [DLW],System,Course viewed,The user with id &#039;54114&#039; viewed the ...,web,103.233.100.203,IF-49-02
2,"20/01/26, 15:53:58",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-02 [DLW],System,Course viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204,IF-49-02
3,"20/01/26, 15:14:42",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-02 [DLW],Logs,Log report viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204,IF-49-02
4,"20/01/26, 15:09:21",HASNAH MUSHAIDAH SOFIA,-,Course: KALKULUS IF-49-02 [DLW],Logs,Log report viewed,The user with id &#039;41146&#039; viewed the ...,web,103.233.100.204,IF-49-02

## Cell 12 — Hitung ringkasan event mentah

In [31]:
jumlah_event_02 = len(log_02_raw)
jumlah_event_03 = len(log_03_raw)
jumlah_event_total = len(log_raw)

print("Jumlah event mentah IF-49-02:", jumlah_event_02)
print("Jumlah event mentah IF-49-03:", jumlah_event_03)
print("Jumlah event mentah total:", jumlah_event_total)

Jumlah event mentah IF-49-02: 89454
Jumlah event mentah IF-49-03: 76192
Jumlah event mentah total: 165646

## Cell 13 — Cek jumlah user unik

In [32]:
print("User unik IF-49-02:", log_02_raw["User full name"].nunique())
print("User unik IF-49-03:", log_03_raw["User full name"].nunique())
print("User unik gabungan:", log_raw["User full name"].nunique())

User unik IF-49-02: 50
User unik IF-49-03: 51
User unik gabungan: 96

## Cell 14 — Lihat daftar user teratas

In [33]:
log_raw["User full name"].value_counts().head(20)

User full name
DEDE TARWIDI                            5539
NAZIFA PUTRI FERIKA                     3477
IMANUEL DENILE BERFY FELIX BOMBANG      3318
RIZKY ALVINO PUTRA                      3265
RAYNISA ZAHRA                           3252
OLIVIA CAHYA DANISWARA                  3103
DENNIS CHRISTOPHER MARIA TITIRLOLOBY    2922
RAFI AJRUR MUZAKKI                      2679
GRADECKAL RAIHAN LABIB                  2622
ADITYA PUTRA PERMANA                    2617
NATHANIEL DARIUS AHMAD RAJA GUKGUK      2444
TIFANY ALISYA MAHARANI                  2364
ASHIFA SUKMANING CAHYA                  2364
ANDREANUS SONDIKA BUTAR BUTAR           2333
MUHAMMAD NUR THOYYIB                    2325
FARIS FATIKHUL IHSAN                    2321
RIZQY PUTRANTO                          2302
MUHAMMAD FADHLURRAHMAN SAFAR            2160
MUHAMMAD FARIEL                         2155
ANJAR AZZAM FADHILAH                    2139
Name: count, dtype: int64

## Cell 15 — Cek aktivitas paling sering

In [34]:
log_raw["Event name"].value_counts().head(30)

Event name
Quiz attempt viewed                              50809
Quiz attempt updated                             49349
Course module viewed                             19636
Course viewed                                    10660
Course activity completion updated                6359
Quiz attempt auto-saved                           5365
User graded                                       4236
Quiz access was prevented                         3521
Grade item updated                                3307
Quiz attempt summary viewed                       2394
Quiz attempt submitted                            2259
Quiz attempt started                              2259
Calendar event updated                            1750
Tag added to an item                              1132
The status of the submission has been viewed.      942
Grade deleted                                      225
Submission form viewed.                            208
Grade user report viewed                           134
Quiz report viewed                                 119
Question category viewed                           116
A submission has been submitted.                   101
A file has been uploaded.                          101
Question viewed                                     90
Submission created.                                 84
Question created                                    81
Course module updated                               69
User list viewed                                    58
Calendar event created                              52
Course user report viewed                           29
Grade item created                                  23
Name: count, dtype: int64

## Cell 16 — Cek component paling sering

In [35]:
log_raw["Component"].value_counts().head(30)

Component
Quiz                              123245
System                             28298
File                                3637
Safe Exam Browser access rules      3521
H5P                                 2638
Assignment                          2512
URL                                  631
Page                                 477
Forum                                321
File submissions                     202
User report                          134
Submission comments                   14
Recycle bin                           10
Logs                                   6
Name: count, dtype: int64

## Cell 17 — Cek format waktu

In [36]:
print(log_raw["Time"].head(10))
print("\nTipe data kolom Time sebelum diubah:")
print(log_raw["Time"].dtype)

0    22/01/26, 15:21:30
1    22/01/26, 15:20:55
2    20/01/26, 15:53:58
3    20/01/26, 15:14:42
4    20/01/26, 15:09:21
5    20/01/26, 15:08:47
6    16/01/26, 22:18:34
7    16/01/26, 18:28:37
8    15/01/26, 23:58:25
9    15/01/26, 23:58:08
Name: Time, dtype: str

Tipe data kolom Time sebelum diubah:
str

## Cell 18 — Ubah Time menjadi datetime untuk analisis waktu

In [39]:
log_raw["Time_parsed"] = pd.to_datetime(
    log_raw["Time"],
    format="%d/%m/%y, %H:%M:%S",
    errors="coerce"
)

print("Tipe data Time_parsed:")
print(log_raw["Time_parsed"].dtype)

print("\nJumlah Time yang gagal dibaca:")
print(log_raw["Time_parsed"].isna().sum())

print("\nTimestamp awal:")
print(log_raw["Time_parsed"].min())

print("\nTimestamp akhir:")
print(log_raw["Time_parsed"].max())

Tipe data Time_parsed:
datetime64[us]

Jumlah Time yang gagal dibaca:
0

Timestamp awal:
2025-09-16 09:49:33

Timestamp akhir:
2026-01-22 15:21:32

## Cell 19 — Cek missing value

In [40]:
missing_values = log_raw.isna().sum().sort_values(ascending=False)

display(missing_values)

IP address        2114
User full name       0
Time                 0
Affected user        0
Event context        0
Event name           0
Component            0
Description          0
Origin               0
kelas                0
Time_parsed          0
dtype: int64

## Cell 20 — Buat tabel ringkasan raw log

In [44]:
summary_raw_log = (
    log_raw
    .groupby("kelas")
    .agg(
        jumlah_event=("Event name", "count"),
        jumlah_user_unik=("User full name", "nunique"),
        jumlah_event_name_unik=("Event name", "nunique"),
        jumlah_component_unik=("Component", "nunique"),
        timestamp_awal=("Time_parsed", "min"),
        timestamp_akhir=("Time_parsed", "max")
    )
    .reset_index()
)

summary_gabungan = pd.DataFrame({
    "kelas": ["Gabungan"],
    "jumlah_event": [len(log_raw)],
    "jumlah_user_unik": [log_raw["User full name"].nunique()],
    "jumlah_event_name_unik": [log_raw["Event name"].nunique()],
    "jumlah_component_unik": [log_raw["Component"].nunique()],
    "timestamp_awal": [log_raw["Time_parsed"].min()],
    "timestamp_akhir": [log_raw["Time_parsed"].max()]
})

summary_raw_log = pd.concat(
    [summary_raw_log, summary_gabungan],
    ignore_index=True
)

display(summary_raw_log)

,kelas,jumlah_event,jumlah_user_unik,jumlah_event_name_unik,jumlah_component_unik,timestamp_awal,timestamp_akhir
0,IF-49-02,89454,50,59,14,2025-09-16 09:49:33,2026-01-22 15:21:30
1,IF-49-03,76192,51,53,14,2025-09-16 14:37:36,2026-01-22 15:21:32
2,Gabungan,165646,96,63,14,2025-09-16 09:49:33,2026-01-22 15:21:32

## Cell 21 — Buat tabel top event name dengan persentase

In [45]:
top_event_name = (
    log_raw["Event name"]
    .value_counts()
    .reset_index()
)

top_event_name.columns = ["event_name", "jumlah_event"]
top_event_name["persentase"] = (
    top_event_name["jumlah_event"] / len(log_raw) * 100
).round(2)

display(top_event_name.head(20))

                                       event_name  jumlah_event  persentase
0                             Quiz attempt viewed         50809       30.67
1                            Quiz attempt updated         49349       29.79
2                            Course module viewed         19636       11.85
3                                   Course viewed         10660        6.44
4              Course activity completion updated          6359        3.84
5                         Quiz attempt auto-saved          5365        3.24
6                                     User graded          4236        2.56
7                       Quiz access was prevented          3521        2.13
8                              Grade item updated          3307        2.00
9                     Quiz attempt summary viewed          2394        1.45
10                         Quiz attempt submitted          2259        1.36
11                           Quiz attempt started          2259        1.36
12                         Calendar event updated          1750        1.06
13                           Tag added to an item          1132        0.68
14  The status of the submission has been viewed.           942        0.57
15                                  Grade deleted           225        0.14
16                        Submission form viewed.           208        0.13
17                       Grade user report viewed           134        0.08
18                             Quiz report viewed           119        0.07
19                       Question category viewed           116        0.07

## Cell 22 — Buat tabel top component dengan persentase

In [46]:
top_component = (
    log_raw["Component"]
    .value_counts()
    .reset_index()
)

top_component.columns = ["component", "jumlah_event"]
top_component["persentase"] = (
    top_component["jumlah_event"] / len(log_raw) * 100
).round(2)

display(top_component.head(20))

                         component  jumlah_event  persentase
0                             Quiz        123245       74.40
1                           System         28298       17.08
2                             File          3637        2.20
3   Safe Exam Browser access rules          3521        2.13
4                              H5P          2638        1.59
5                       Assignment          2512        1.52
6                              URL           631        0.38
7                             Page           477        0.29
8                            Forum           321        0.19
9                 File submissions           202        0.12
10                     User report           134        0.08
11             Submission comments            14        0.01
12                     Recycle bin            10        0.01
13                            Logs             6        0.00

## Cell 23 — Simpan tabel ke outputs/tables

In [47]:
TABLES_DIR = PROJECT_ROOT / "outputs" / "tables"
TABLES_DIR.mkdir(parents=True, exist_ok=True)

summary_raw_log.to_csv(TABLES_DIR / "01_summary_raw_log.csv", index=False)
top_event_name.to_csv(TABLES_DIR / "01_top_event_name_raw.csv", index=False)
top_component.to_csv(TABLES_DIR / "01_top_component_raw.csv", index=False)

print("Tabel berhasil disimpan ke:", TABLES_DIR)

Tabel berhasil disimpan ke: e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\outputs\tables

## Kesimpulan Data Understanding

Pada tahap data understanding, dua file log LMS dari kelas IF-49-02 dan IF-49-03 berhasil dibaca dan digabungkan. Total data mentah terdiri dari 165.646 event dengan 10 kolom setelah penambahan atribut kelas. Kolom utama yang tersedia meliputi Time, User full name, Event context, Component, Event name, Description, Origin, dan IP address.

Hasil pemeriksaan awal menunjukkan bahwa terdapat 96 user unik pada raw log gabungan. Jumlah ini lebih besar dibandingkan jumlah mahasiswa pada data nilai resmi, sehingga raw log masih mengandung aktivitas dari user selain mahasiswa, seperti dosen, admin, atau aktivitas sistem. Oleh karena itu, tahap preprocessing berikutnya perlu melakukan penyaringan user berdasarkan daftar mahasiswa pada data nilai.

Distribusi aktivitas menunjukkan bahwa raw log didominasi oleh aktivitas kuis. Event name dengan frekuensi tertinggi adalah Quiz attempt viewed dan Quiz attempt updated. Dari sisi Component, komponen Quiz juga menjadi komponen paling dominan. Hal ini menunjukkan bahwa interaksi mahasiswa pada LMS banyak terjadi pada aktivitas evaluasi atau pengerjaan kuis.

Kolom Time berhasil dikonversi menjadi format datetime tanpa nilai gagal parsing. Selain itu, kolom utama yang diperlukan untuk process mining, yaitu User full name, Event name, Component, dan Time, tidak memiliki missing value. Dengan demikian, data mentah memiliki struktur yang memadai untuk dilanjutkan ke tahap persiapan label dan preprocessing event log.