# Cell 1 — Import library

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Cell 2 — Tentukan folder project

In [2]:
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data"
PROCESSED_DIR = DATA_DIR / "processed"
OUTPUT_TABLES_DIR = PROJECT_ROOT / "outputs" / "tables"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_TABLES_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Processed dir:", PROCESSED_DIR)
print("Output tables dir:", OUTPUT_TABLES_DIR)

Project root: e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL
Processed dir: e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\data\processed
Output tables dir: e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\outputs\tables

# Cell 3 — Baca full log, compact log, dan trace fitness

In [3]:
FULL_LOG_PATH = PROCESSED_DIR / "04_full_log_process_ready.csv"
COMPACT_LOG_PATH = PROCESSED_DIR / "04_compact_log_process_ready.csv"
TRACE_FITNESS_PATH = PROCESSED_DIR / "07_trace_fitness_main_learning.csv"

full_log = pd.read_csv(FULL_LOG_PATH, parse_dates=["timestamp"])
compact_log = pd.read_csv(COMPACT_LOG_PATH, parse_dates=["timestamp"])
trace_fitness = pd.read_csv(TRACE_FITNESS_PATH)

print("Full log:", full_log.shape)
print("Compact log:", compact_log.shape)
print("Trace fitness:", trace_fitness.shape)

display(full_log.head())
display(compact_log.head())
display(trace_fitness.head())

Full log: (147249, 17)
Compact log: (116611, 18)
Trace fitness: (89, 13)

,case_id,activity,timestamp,kelas,Component,Event context,Description,Origin,IP address,nim,nama,nilai_total,nilai_indeks,label_performance,activity_mapped,activity_category,event_order
0,ADITYA PUTRA PERMANA,Course viewed,2025-09-18 13:30:09,IF-49-02,System,Course: KALKULUS IF-49-02 [DLW],The user with id &#039;124462&#039; viewed the...,web,103.233.100.204,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Course Viewed,course,1
1,ADITYA PUTRA PERMANA,Course viewed,2025-09-18 13:31:17,IF-49-02,System,Course: KALKULUS IF-49-02 [DLW],The user with id &#039;124462&#039; viewed the...,web,103.233.100.203,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Course Viewed,course,2
2,ADITYA PUTRA PERMANA,Course viewed,2025-09-18 13:39:55,IF-49-02,System,Course: KALKULUS IF-49-02 [DLW],The user with id &#039;124462&#039; viewed the...,web,103.233.100.202,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Course Viewed,course,3
3,ADITYA PUTRA PERMANA,Course module viewed,2025-09-18 14:24:42,IF-49-02,File,File: Materi 1 Sistem Bilangan Riil dan Pertak...,The user with id &#039;124462&#039; viewed the...,web,103.233.100.202,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Material Viewed,material,4
4,ADITYA PUTRA PERMANA,Course viewed,2025-09-18 15:41:24,IF-49-02,System,Course: KALKULUS IF-49-02 [DLW],The user with id &#039;124462&#039; viewed the...,web,103.233.100.202,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Course Viewed,course,5

,case_id,activity,timestamp,kelas,Component,Event context,Description,Origin,IP address,nim,nama,nilai_total,nilai_indeks,label_performance,activity_mapped,activity_category,event_order,compact_event_order
0,ADITYA PUTRA PERMANA,Course viewed,2025-09-18 13:30:09,IF-49-02,System,Course: KALKULUS IF-49-02 [DLW],The user with id &#039;124462&#039; viewed the...,web,103.233.100.204,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Course Viewed,course,1,1
1,ADITYA PUTRA PERMANA,Course module viewed,2025-09-18 14:24:42,IF-49-02,File,File: Materi 1 Sistem Bilangan Riil dan Pertak...,The user with id &#039;124462&#039; viewed the...,web,103.233.100.202,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Material Viewed,material,4,2
2,ADITYA PUTRA PERMANA,Course viewed,2025-09-18 15:41:24,IF-49-02,System,Course: KALKULUS IF-49-02 [DLW],The user with id &#039;124462&#039; viewed the...,web,103.233.100.202,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Course Viewed,course,5,3
3,ADITYA PUTRA PERMANA,Course module viewed,2025-09-18 15:41:57,IF-49-02,File,File: Materi 1 Sistem Bilangan Riil dan Pertak...,The user with id &#039;124462&#039; viewed the...,web,103.233.100.202,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Material Viewed,material,6,4
4,ADITYA PUTRA PERMANA,Course viewed,2025-09-18 16:40:55,IF-49-02,System,Course: KALKULUS IF-49-02 [DLW],The user with id &#039;124462&#039; viewed the...,web,36.72.198.4,103012530065,ADITYA PUTRA PERMANA,73.01,B,Sedang,Course Viewed,course,7,5

,case_id,trace_is_fit,trace_fitness,missing_tokens,consumed_tokens,remaining_tokens,produced_tokens,nim,nama,kelas,nilai_total,nilai_indeks,label_performance
0,ADITYA PUTRA PERMANA,True,1.0,0,3866,0,3866,103012530065,ADITYA PUTRA PERMANA,IF-49-02,73.01,B,Sedang
1,ADY RAHMAN WICAKSONO,True,1.0,0,2096,0,2096,103012500077,ADY RAHMAN WICAKSONO,IF-49-03,60.04,BC,Sedang
2,AGUNG KALEB SASAUW,True,1.0,0,2488,0,2488,103012500211,AGUNG KALEB SASAUW,IF-49-03,75.04,AB,Tinggi
3,ALFITO MAULANA,True,1.0,0,1856,0,1856,103012530032,ALFITO MAULANA,IF-49-03,67.24,B,Sedang
4,ALFONSUS LIGUORI DANGO,True,1.0,0,1684,0,1684,103012580046,ALFONSUS LIGUORI DANGO,IF-49-02,40.28,D,Rendah

# Cell 4 — Validasi data

In [4]:
print("Jumlah mahasiswa full log:", full_log["case_id"].nunique())
print("Jumlah mahasiswa compact log:", compact_log["case_id"].nunique())
print("Jumlah mahasiswa trace fitness:", trace_fitness["case_id"].nunique())

print("\nJumlah activity full log:", full_log["activity_mapped"].nunique())
print("Jumlah activity compact log:", compact_log["activity_mapped"].nunique())

print("\nDistribusi label performance di full log:")
display(full_log["label_performance"].value_counts())

Jumlah mahasiswa full log: 89
Jumlah mahasiswa compact log: 89
Jumlah mahasiswa trace fitness: 89

Jumlah activity full log: 25
Jumlah activity compact log: 25

Distribusi label performance di full log:

label_performance
Sedang    93906
Tinggi    38330
Rendah    15013
Name: count, dtype: int64

# Cell 5 — Buat data dasar mahasiswa

In [5]:
student_base = (
    full_log[[
        "case_id",
        "nim",
        "nama",
        "kelas",
        "nilai_total",
        "nilai_indeks",
        "label_performance"
    ]]
    .drop_duplicates()
    .sort_values("case_id")
    .reset_index(drop=True)
)

print("Ukuran student_base:", student_base.shape)
display(student_base.head())

print("\nDistribusi label mahasiswa:")
display(student_base["label_performance"].value_counts())

Ukuran student_base: (89, 7)

,case_id,nim,nama,kelas,nilai_total,nilai_indeks,label_performance
0,ADITYA PUTRA PERMANA,103012530065,ADITYA PUTRA PERMANA,IF-49-02,73.01,B,Sedang
1,ADY RAHMAN WICAKSONO,103012500077,ADY RAHMAN WICAKSONO,IF-49-03,60.04,BC,Sedang
2,AGUNG KALEB SASAUW,103012500211,AGUNG KALEB SASAUW,IF-49-03,75.04,AB,Tinggi
3,ALFITO MAULANA,103012530032,ALFITO MAULANA,IF-49-03,67.24,B,Sedang
4,ALFONSUS LIGUORI DANGO,103012580046,ALFONSUS LIGUORI DANGO,IF-49-02,40.28,D,Rendah

Distribusi label mahasiswa:

label_performance
Sedang    54
Tinggi    20
Rendah    15
Name: count, dtype: int64

# Cell 6 — Fitur jumlah event dan aktivitas unik

In [6]:
basic_features_full = (
    full_log
    .groupby("case_id")
    .agg(
        total_events_full=("activity_mapped", "count"),
        unique_activity_full=("activity_mapped", "nunique")
    )
    .reset_index()
)

basic_features_compact = (
    compact_log
    .groupby("case_id")
    .agg(
        total_events_compact=("activity_mapped", "count"),
        unique_activity_compact=("activity_mapped", "nunique")
    )
    .reset_index()
)

basic_features = basic_features_full.merge(
    basic_features_compact,
    on="case_id",
    how="left"
)

basic_features["compression_ratio"] = (
    basic_features["total_events_compact"] / basic_features["total_events_full"]
).round(4)

display(basic_features.head())

print("Ringkasan basic features:")
display(basic_features.describe().round(2))

,case_id,total_events_full,unique_activity_full,total_events_compact,unique_activity_compact,compression_ratio
0,ADITYA PUTRA PERMANA,2413,17,1979,17,0.8201
1,ADY RAHMAN WICAKSONO,1460,17,1086,17,0.7438
2,AGUNG KALEB SASAUW,1612,17,1266,17,0.7854
3,ALFITO MAULANA,1181,17,948,17,0.8027
4,ALFONSUS LIGUORI DANGO,1000,12,844,12,0.8440

Ringkasan basic features:

,total_events_full,unique_activity_full,total_events_compact,unique_activity_compact,compression_ratio
count,89.00,89.00,89.00,89.00,89.00
mean,1654.48,16.74,1310.24,16.74,0.79
std,602.89,1.64,477.76,1.64,0.03
min,61.00,9.00,51.00,9.00,0.66
25%,1330.00,16.00,1055.00,16.00,0.78
50%,1610.00,17.00,1263.00,17.00,0.80
75%,1903.00,17.00,1517.00,17.00,0.82
max,3352.00,21.00,2574.00,21.00,0.85

# Cell 7 — Fitur waktu aktivitas

In [7]:
full_log["date"] = full_log["timestamp"].dt.date

time_features = (
    full_log
    .groupby("case_id")
    .agg(
        first_timestamp=("timestamp", "min"),
        last_timestamp=("timestamp", "max"),
        active_days=("date", "nunique")
    )
    .reset_index()
)

time_features["activity_span_days"] = (
    (time_features["last_timestamp"] - time_features["first_timestamp"]).dt.days + 1
)

time_features["avg_events_per_active_day"] = (
    basic_features_full.set_index("case_id")["total_events_full"]
    / time_features.set_index("case_id")["active_days"]
).values

time_features["avg_events_per_active_day"] = time_features["avg_events_per_active_day"].round(2)

display(time_features.head())

print("Ringkasan time features:")
display(time_features[[
    "active_days",
    "activity_span_days",
    "avg_events_per_active_day"
]].describe().round(2))

,case_id,first_timestamp,last_timestamp,active_days,activity_span_days,avg_events_per_active_day
0,ADITYA PUTRA PERMANA,2025-09-18 13:30:09,2026-01-16 22:18:34,63,121,38.30
1,ADY RAHMAN WICAKSONO,2025-09-16 14:37:36,2026-01-12 11:55:41,44,118,33.18
2,AGUNG KALEB SASAUW,2025-09-17 14:17:49,2026-01-12 11:21:39,47,117,34.30
3,ALFITO MAULANA,2025-09-21 15:18:01,2026-01-12 11:31:52,37,113,31.92
4,ALFONSUS LIGUORI DANGO,2025-09-18 14:28:54,2026-01-12 11:44:32,25,116,40.00

Ringkasan time features:

       active_days  activity_span_days  avg_events_per_active_day
count        89.00               89.00                      89.00
mean         44.22              114.06                      37.13
std          12.65               12.91                       8.99
min           3.00               22.00                      19.08
25%          38.00              115.00                      31.20
50%          45.00              116.00                      37.00
75%          50.00              117.00                      41.91
max          75.00              122.00                      66.93

# Cell 8 — Fitur frekuensi kategori aktivitas

In [8]:
category_counts = (
    full_log
    .groupby(["case_id", "activity_category"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

category_counts = category_counts.rename(columns={
    "course": "freq_course",
    "material": "freq_material",
    "quiz": "freq_quiz",
    "assignment": "freq_assignment",
    "forum": "freq_forum"
})

expected_category_cols = [
    "freq_course",
    "freq_material",
    "freq_quiz",
    "freq_assignment",
    "freq_forum"
]

for col in expected_category_cols:
    if col not in category_counts.columns:
        category_counts[col] = 0

category_counts = category_counts[["case_id"] + expected_category_cols]

display(category_counts.head())

activity_category,case_id,freq_course,freq_material,freq_quiz,freq_assignment,freq_forum
0,ADITYA PUTRA PERMANA,166,122,2071,42,12
1,ADY RAHMAN WICAKSONO,159,97,1160,38,6
2,AGUNG KALEB SASAUW,95,141,1348,16,12
3,ALFITO MAULANA,74,54,1028,20,5
4,ALFONSUS LIGUORI DANGO,63,33,898,6,0

# Cell 9 — Rasio kategori aktivitas

In [9]:
category_ratio = category_counts.copy()

category_ratio = category_ratio.merge(
    basic_features_full,
    on="case_id",
    how="left"
)

for col in expected_category_cols:
    ratio_col = col.replace("freq_", "ratio_")
    category_ratio[ratio_col] = (
        category_ratio[col] / category_ratio["total_events_full"]
    ).round(4)

category_ratio = category_ratio[[
    "case_id",
    "ratio_course",
    "ratio_material",
    "ratio_quiz",
    "ratio_assignment",
    "ratio_forum"
]]

display(category_ratio.head())

,case_id,ratio_course,ratio_material,ratio_quiz,ratio_assignment,ratio_forum
0,ADITYA PUTRA PERMANA,0.0688,0.0506,0.8583,0.0174,0.0050
1,ADY RAHMAN WICAKSONO,0.1089,0.0664,0.7945,0.0260,0.0041
2,AGUNG KALEB SASAUW,0.0589,0.0875,0.8362,0.0099,0.0074
3,ALFITO MAULANA,0.0627,0.0457,0.8704,0.0169,0.0042
4,ALFONSUS LIGUORI DANGO,0.0630,0.0330,0.8980,0.0060,0.0000

# Cell 10 — Fitur aktivitas spesifik

In [10]:
activity_counts = (
    full_log
    .groupby(["case_id", "activity_mapped"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

activity_feature_mapping = {
    "Course Viewed": "act_course_viewed",
    "Material Viewed": "act_material_viewed",
    "Quiz Module Viewed": "act_quiz_module_viewed",
    "Quiz Access Prevented": "act_quiz_access_prevented",
    "Quiz Started": "act_quiz_started",
    "Quiz Viewed": "act_quiz_viewed",
    "Quiz Updated": "act_quiz_updated",
    "Quiz Auto-saved": "act_quiz_auto_saved",
    "Quiz Summary Viewed": "act_quiz_summary_viewed",
    "Quiz Submitted": "act_quiz_submitted",
    "Assignment Viewed": "act_assignment_viewed",
    "Assignment Status Viewed": "act_assignment_status_viewed",
    "Forum Viewed": "act_forum_viewed"
}

activity_specific_features = pd.DataFrame()
activity_specific_features["case_id"] = activity_counts["case_id"]

for original_activity, feature_name in activity_feature_mapping.items():
    if original_activity in activity_counts.columns:
        activity_specific_features[feature_name] = activity_counts[original_activity]
    else:
        activity_specific_features[feature_name] = 0

display(activity_specific_features.head())

,case_id,act_course_viewed,act_material_viewed,act_quiz_module_viewed,act_quiz_access_prevented,act_quiz_started,act_quiz_viewed,act_quiz_updated,act_quiz_auto_saved,act_quiz_summary_viewed,act_quiz_submitted,act_assignment_viewed,act_assignment_status_viewed,act_forum_viewed
0,ADITYA PUTRA PERMANA,166,122,152,42,24,856,831,121,21,24,20,18,12
1,ADY RAHMAN WICAKSONO,159,97,133,47,27,435,425,36,30,27,18,16,6
2,AGUNG KALEB SASAUW,95,141,162,30,28,521,488,65,27,27,7,3,12
3,ALFITO MAULANA,74,54,111,32,24,404,389,22,23,23,9,7,5
4,ALFONSUS LIGUORI DANGO,63,33,78,24,17,353,348,44,17,17,3,3,0

# Cell 11 — Fitur transisi dari compact log

In [11]:
compact_sorted = compact_log.sort_values(
    by=["case_id", "timestamp"]
).copy()

compact_sorted["next_activity"] = (
    compact_sorted
    .groupby("case_id")["activity_mapped"]
    .shift(-1)
)

transitions_student = compact_sorted.dropna(subset=["next_activity"]).copy()

transition_basic_features = (
    transitions_student
    .groupby("case_id")
    .agg(
        total_transition=("next_activity", "count")
    )
    .reset_index()
)

unique_transition_features = (
    transitions_student
    .assign(
        transition_pair=transitions_student["activity_mapped"] + " -> " + transitions_student["next_activity"]
    )
    .groupby("case_id")
    .agg(
        unique_transition_count=("transition_pair", "nunique")
    )
    .reset_index()
)

transition_features = transition_basic_features.merge(
    unique_transition_features,
    on="case_id",
    how="left"
)

display(transition_features.head())

print("Ringkasan transition features:")
display(transition_features.describe().round(2))

                  case_id  total_transition  unique_transition_count
0    ADITYA PUTRA PERMANA              1978                       65
1    ADY RAHMAN WICAKSONO              1085                       57
2      AGUNG KALEB SASAUW              1265                       58
3          ALFITO MAULANA               947                       54
4  ALFONSUS LIGUORI DANGO               843                       36

Ringkasan transition features:

       total_transition  unique_transition_count
count             89.00                    89.00
mean            1309.24                    56.19
std              477.76                     9.48
min               50.00                    15.00
25%             1054.00                    53.00
50%             1262.00                    58.00
75%             1516.00                    61.00
max             2573.00                    85.00

# Cell 12 — Fitur transisi spesifik utama

In [12]:
transitions_student["transition_pair"] = (
    transitions_student["activity_mapped"] + " -> " + transitions_student["next_activity"]
)

transition_counts = (
    transitions_student
    .groupby(["case_id", "transition_pair"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

important_transitions = {
    "Course Viewed -> Material Viewed": "tr_course_to_material",
    "Course Viewed -> Quiz Module Viewed": "tr_course_to_quiz_module",
    "Material Viewed -> Course Viewed": "tr_material_to_course",
    "Quiz Module Viewed -> Course Viewed": "tr_quiz_module_to_course",
    "Quiz Module Viewed -> Quiz Viewed": "tr_quiz_module_to_quiz_viewed",
    "Quiz Module Viewed -> Quiz Started": "tr_quiz_module_to_quiz_started",
    "Quiz Started -> Quiz Viewed": "tr_quiz_started_to_quiz_viewed",
    "Quiz Viewed -> Quiz Updated": "tr_quiz_viewed_to_quiz_updated",
    "Quiz Updated -> Quiz Viewed": "tr_quiz_updated_to_quiz_viewed",
    "Quiz Updated -> Quiz Auto-saved": "tr_quiz_updated_to_auto_saved",
    "Quiz Auto-saved -> Quiz Viewed": "tr_auto_saved_to_quiz_viewed",
    "Quiz Updated -> Quiz Summary Viewed": "tr_quiz_updated_to_summary",
    "Quiz Summary Viewed -> Quiz Submitted": "tr_summary_to_submitted",
    "Quiz Submitted -> Quiz Module Viewed": "tr_submitted_to_quiz_module"
}

transition_specific_features = pd.DataFrame()
transition_specific_features["case_id"] = transition_counts["case_id"]

for transition_name, feature_name in important_transitions.items():
    if transition_name in transition_counts.columns:
        transition_specific_features[feature_name] = transition_counts[transition_name]
    else:
        transition_specific_features[feature_name] = 0

display(transition_specific_features.head())

,case_id,tr_course_to_material,tr_course_to_quiz_module,tr_material_to_course,tr_quiz_module_to_course,tr_quiz_module_to_quiz_viewed,tr_quiz_module_to_quiz_started,tr_quiz_started_to_quiz_viewed,tr_quiz_viewed_to_quiz_updated,tr_quiz_updated_to_quiz_viewed,tr_quiz_updated_to_auto_saved,tr_auto_saved_to_quiz_viewed,tr_quiz_updated_to_summary,tr_summary_to_submitted,tr_submitted_to_quiz_module
0,ADITYA PUTRA PERMANA,52,34,40,54,31,7,16,670,611,69,74,19,14,22
1,ADY RAHMAN WICAKSONO,35,22,29,25,27,7,18,322,295,16,16,30,16,20
2,AGUNG KALEB SASAUW,55,13,34,29,36,11,18,376,345,29,35,27,23,26
3,ALFITO MAULANA,16,32,15,40,22,11,18,298,280,10,7,21,15,23
4,ALFONSUS LIGUORI DANGO,21,17,16,24,17,5,15,292,253,27,29,16,10,15

# Cell 13 — Fitur variant dari compact log

In [13]:
variant_df = (
    compact_log
    .sort_values(["case_id", "timestamp"])
    .groupby("case_id")["activity_mapped"]
    .apply(lambda activities: " -> ".join(activities))
    .reset_index(name="variant_sequence")
)

variant_counts = (
    variant_df["variant_sequence"]
    .value_counts()
    .reset_index()
)

variant_counts.columns = ["variant_sequence", "variant_frequency"]
variant_counts["variant_id"] = range(1, len(variant_counts) + 1)

variant_features = variant_df.merge(
    variant_counts,
    on="variant_sequence",
    how="left"
)

variant_features = variant_features[[
    "case_id",
    "variant_id",
    "variant_frequency",
    "variant_sequence"
]]

display(variant_features.head())

print("Jumlah variant unik:", variant_features["variant_id"].nunique())
print("Top 10 variant:")
display(variant_counts.head(10))

,case_id,variant_id,variant_frequency,variant_sequence
0,ADITYA PUTRA PERMANA,1,1,Course Viewed -> Material Viewed -> Course Vie...
1,ADY RAHMAN WICAKSONO,2,1,Course Viewed -> Material Viewed -> Assignment...
2,AGUNG KALEB SASAUW,3,1,Course Viewed -> Material Viewed -> Course Vie...
3,ALFITO MAULANA,4,1,Quiz Module Viewed -> Material Viewed -> Quiz ...
4,ALFONSUS LIGUORI DANGO,5,1,Course Viewed -> Material Viewed -> Course Vie...

Jumlah variant unik: 89
Top 10 variant:

,variant_sequence,variant_frequency,variant_id
0,Course Viewed -> Material Viewed -> Course Vie...,1,1
1,Course Viewed -> Material Viewed -> Assignment...,1,2
2,Course Viewed -> Material Viewed -> Course Vie...,1,3
3,Quiz Module Viewed -> Material Viewed -> Quiz ...,1,4
4,Course Viewed -> Material Viewed -> Course Vie...,1,5
5,Course Viewed -> Material Viewed -> Course Vie...,1,6
6,Course Viewed -> Material Viewed -> Course Vie...,1,7
7,Assignment Status Viewed -> Assignment Viewed ...,1,8
8,Course Viewed -> Material Viewed -> Course Vie...,1,9
9,Course Viewed -> Material Viewed -> Course Vie...,1,10

# Cell 14 — Rapikan trace fitness

In [14]:
trace_fitness_features = trace_fitness[[
    "case_id",
    "trace_is_fit",
    "trace_fitness",
    "missing_tokens",
    "remaining_tokens",
    "consumed_tokens",
    "produced_tokens"
]].copy()

trace_fitness_features["trace_is_fit"] = trace_fitness_features["trace_is_fit"].astype(int)

display(trace_fitness_features.head())

,case_id,trace_is_fit,trace_fitness,missing_tokens,remaining_tokens,consumed_tokens,produced_tokens
0,ADITYA PUTRA PERMANA,1,1.0,0,0,3866,3866
1,ADY RAHMAN WICAKSONO,1,1.0,0,0,2096,2096
2,AGUNG KALEB SASAUW,1,1.0,0,0,2488,2488
3,ALFITO MAULANA,1,1.0,0,0,1856,1856
4,ALFONSUS LIGUORI DANGO,1,1.0,0,0,1684,1684

# Cell 15 — Gabungkan semua fitur

In [17]:
feature_df = student_base.copy()

feature_tables = [
    basic_features,
    time_features,
    category_counts,
    category_ratio,
    activity_specific_features,
    transition_features,
    transition_specific_features,
    variant_features,
    trace_fitness_features
]

for table in feature_tables:
    feature_df = feature_df.merge(
        table,
        on="case_id",
        how="left"
    )

print("Ukuran feature_df:", feature_df.shape)
display(feature_df.head())

Ukuran feature_df: (89, 65)

,case_id,nim,nama,kelas,nilai_total,nilai_indeks,label_performance,total_events_full,unique_activity_full,total_events_compact,...,tr_submitted_to_quiz_module,variant_id,variant_frequency,variant_sequence,trace_is_fit,trace_fitness,missing_tokens,remaining_tokens,consumed_tokens,produced_tokens
0,ADITYA PUTRA PERMANA,103012530065,ADITYA PUTRA PERMANA,IF-49-02,73.01,B,Sedang,2413,17,1979,...,22,1,1,Course Viewed -> Material Viewed -> Course Vie...,1,1.0,0,0,3866,3866
1,ADY RAHMAN WICAKSONO,103012500077,ADY RAHMAN WICAKSONO,IF-49-03,60.04,BC,Sedang,1460,17,1086,...,20,2,1,Course Viewed -> Material Viewed -> Assignment...,1,1.0,0,0,2096,2096
2,AGUNG KALEB SASAUW,103012500211,AGUNG KALEB SASAUW,IF-49-03,75.04,AB,Tinggi,1612,17,1266,...,26,3,1,Course Viewed -> Material Viewed -> Course Vie...,1,1.0,0,0,2488,2488
3,ALFITO MAULANA,103012530032,ALFITO MAULANA,IF-49-03,67.24,B,Sedang,1181,17,948,...,23,4,1,Quiz Module Viewed -> Material Viewed -> Quiz ...,1,1.0,0,0,1856,1856
4,ALFONSUS LIGUORI DANGO,103012580046,ALFONSUS LIGUORI DANGO,IF-49-02,40.28,D,Rendah,1000,12,844,...,15,5,1,Course Viewed -> Material Viewed -> Course Vie...,1,1.0,0,0,1684,1684

# Cell 16 — Cek missing value

In [18]:
missing_features = feature_df.isna().sum()
missing_features = missing_features[missing_features > 0].sort_values(ascending=False)

print("Jumlah kolom dengan missing value:", len(missing_features))
display(missing_features)

Jumlah kolom dengan missing value: 0

Series([], dtype: int64)

# Cell 17 — Isi missing numerik dan cek tipe data

In [19]:
numeric_cols = feature_df.select_dtypes(include=["number"]).columns

feature_df[numeric_cols] = feature_df[numeric_cols].fillna(0)

print("Missing value setelah fill numeric:")
display(feature_df.isna().sum()[feature_df.isna().sum() > 0])

print("\nTipe data:")
display(feature_df.dtypes)

Missing value setelah fill numeric:

Series([], dtype: int64)

Tipe data:

case_id                 str
nim                   int64
nama                    str
kelas                   str
nilai_total         float64
                     ...
trace_fitness       float64
missing_tokens        int64
remaining_tokens      int64
consumed_tokens       int64
produced_tokens       int64
Length: 65, dtype: object

# Cell 18 — Simpan dataset fitur

In [20]:
FEATURE_OUTPUT_PATH = PROCESSED_DIR / "08_features_process_mining_per_student.csv"
FEATURE_TABLE_OUTPUT_PATH = OUTPUT_TABLES_DIR / "08_features_process_mining_per_student.csv"

feature_df.to_csv(FEATURE_OUTPUT_PATH, index=False)
feature_df.to_csv(FEATURE_TABLE_OUTPUT_PATH, index=False)

print("Dataset fitur berhasil disimpan ke:")
print(FEATURE_OUTPUT_PATH)
print(FEATURE_TABLE_OUTPUT_PATH)

Dataset fitur berhasil disimpan ke:
e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\data\processed\08_features_process_mining_per_student.csv
e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\outputs\tables\08_features_process_mining_per_student.csv

# Cell 19 — Ringkasan fitur berdasarkan label

In [21]:
summary_by_label = (
    feature_df
    .groupby("label_performance")
    .agg(
        jumlah_mahasiswa=("case_id", "count"),
        avg_total_events=("total_events_full", "mean"),
        avg_active_days=("active_days", "mean"),
        avg_freq_quiz=("freq_quiz", "mean"),
        avg_freq_material=("freq_material", "mean"),
        avg_freq_assignment=("freq_assignment", "mean"),
        avg_unique_activity=("unique_activity_full", "mean"),
        avg_unique_transition=("unique_transition_count", "mean")
    )
    .round(2)
    .reset_index()
)

display(summary_by_label)

SUMMARY_BY_LABEL_PATH = OUTPUT_TABLES_DIR / "08_summary_features_by_label.csv"
summary_by_label.to_csv(SUMMARY_BY_LABEL_PATH, index=False)

print("Ringkasan fitur per label berhasil disimpan ke:")
print(SUMMARY_BY_LABEL_PATH)

,label_performance,jumlah_mahasiswa,avg_total_events,avg_active_days,avg_freq_quiz,avg_freq_material,avg_freq_assignment,avg_unique_activity,avg_unique_transition
0,Rendah,15,1000.87,30.33,866.60,39.80,22.80,15.27,46.27
1,Sedang,54,1739.00,46.09,1513.13,78.02,31.76,16.94,57.78
2,Tinggi,20,1916.50,49.60,1586.00,126.65,31.55,17.30,59.35

Ringkasan fitur per label berhasil disimpan ke:
e:\Tugas Akhir\Coding\TA_PROCESS_MINING_FINAL\outputs\tables\08_summary_features_by_label.csv

## Kesimpulan Feature Extraction

Pada tahap ini, event log hasil process mining diubah menjadi fitur proses pada tingkat mahasiswa. Dataset fitur akhir terdiri dari 89 mahasiswa dengan 65 kolom, yang mencakup identitas mahasiswa, label performa akademik, fitur jumlah event, fitur waktu aktivitas, frekuensi kategori aktivitas, rasio kategori aktivitas, aktivitas spesifik, transisi aktivitas, variant, serta hasil conformance checking.

Hasil ekstraksi fitur menunjukkan bahwa kelompok mahasiswa dengan performa Tinggi cenderung memiliki rata-rata jumlah event yang lebih besar dibandingkan kelompok Sedang dan Rendah. Kelompok Tinggi juga memiliki rata-rata hari aktif, frekuensi aktivitas kuis, frekuensi akses material, jumlah aktivitas unik, dan jumlah transisi unik yang lebih tinggi. Hal ini menunjukkan bahwa mahasiswa dengan performa lebih tinggi memiliki kecenderungan interaksi LMS yang lebih intensif dan lebih bervariasi.

Selain itu, hasil variant analysis menunjukkan bahwa terdapat 89 variant unik dari 89 mahasiswa. Temuan ini menunjukkan bahwa setiap mahasiswa memiliki urutan aktivitas belajar yang berbeda. Dengan demikian, proses belajar mahasiswa pada LMS bersifat sangat bervariasi dan tidak mengikuti satu alur yang sama secara kaku.

Hasil conformance checking berupa trace fitness tetap disimpan sebagai bagian dari fitur proses. Namun, karena seluruh trace memiliki nilai fitness 1,0, fitur tersebut tidak membedakan kelompok performa akademik. Oleh karena itu, fitur yang lebih informatif untuk tahap machine learning adalah fitur frekuensi aktivitas, durasi aktivitas, kategori aktivitas, dan pola transisi aktivitas.

Dataset fitur akhir disimpan sebagai `data/processed/08_features_process_mining_per_student.csv` dan akan digunakan pada tahap analisis pola performa serta pemodelan machine learning.